name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 🚚 Deploy files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: domains/sonatalodge.com/public_html/  # Đường dẫn đến thư mục chứa code web của bạn


          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
            **/logs/**
            **/.DS_Store
            **/wp-content/cache/**
            **/wp-content/uploads/**